server:
  port: 8080  # Porta na qual a aplicação será executada
  servlet:
    context-path: /api  # Caminho base do contexto da aplicação

spring:
  datasource:
    url: ${MYSQL_DATABASE_URL:jdbc:mysql://localhost:3306/condominio}
    username: ${MYSQL_USER_NAME:root}
    password: ${MYSQL_PASSWORD:mysql}
    hikari:
      maximum-pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Desativa o gerenciamento do esquema pelo Hibernate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:db/changelogs/db.changelog.master.xml
  test:
    database:
      replace: none

  mail:
    host: localhost
    port: 25
    protocol: smtp

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework: FATAL
    com.github: ERROR
    com.pmrodrigues: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'  # Expõe todos os endpoints do Actuator
  endpoint:
    health:
      show-details: always  # Exibe detalhes de saúde sempre que possível

jwt:
  secret: ${SECRET_KEY:mZdpX2b3p9FlqZj3bY9rPlO6HQlZ/7W8F4ER6CfOtrg=}
  expiration: 1200000
