name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # Trigger for all branches
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run unit tests
      run: mvn test

    - name: Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
        detailed_summary: true
        include_passed: true

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run Database Migrations
      run: |
        mvn liquibase:update

    - name: Deploy to Environment
      run: |
        if [ "${{ github.base_ref }}" == "main" ]; then
          echo "Deploying to production environment..."
          # Script to deploy application to production server
        elif [ "${{ github.base_ref }}" == "develop" ]; then
          echo "Deploying to staging environment..."
          # Script to deploy application to staging server
        fi

    - name: Run Tests on Environment
      run: |
        if [ "${{ github.base_ref }}" == "main" ]; then
          echo "Running smoke tests on production..."
          # Execute smoke tests or end-to-end tests
        elif [ "${{ github.base_ref }}" == "develop" ]; then
          echo "Running integration tests on staging..."
          # Execute integration tests on staging
        fi
